spring.application.name=todoapi

spring.datasource.url=jdbc:postgresql://localhost:5432/todo_api_v1
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrationv